"""
Django settings for fengshui project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-dev-only-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG=False explicitly in production, or use DJANGO_DEBUG env var
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'myfate.org', 'web']  # 'web' for Docker health checks

# CSRF trusted origins (required for POST requests via HTTPS)
CSRF_TRUSTED_ORIGINS = ['https://myfate.org']

# Production Security Settings
if not DEBUG:
    # HTTPS/SSL (Traefik handles SSL termination)
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_REDIRECT_EXEMPT = [r'^health/$']  # Exempt health check from SSL redirect

    # HSTS - tell browsers to only use HTTPS
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Cookie Security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Additional Security Headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# Application definition

INSTALLED_APPS = [
    'bazi',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required by django-allauth
    # Authentication (django-allauth)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.apple',
    # Frontend modernization (Vite + HTMX + Alpine + React Islands)
    'django_vite',
    'django_htmx',
    'django_browser_reload',
    # Development tools
    'django_extensions',
]

# Required by django-allauth
SITE_ID = 1

# Internal IPs for debug toolbar and browser reload
INTERNAL_IPS = ['127.0.0.1']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # i18n - must be after SessionMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # django-allauth
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Frontend modernization
    'django_htmx.middleware.HtmxMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
]

ROOT_URLCONF = 'fengshui.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',  # For LANGUAGE_CODE in templates
            ],
        },
    },
]

WSGI_APPLICATION = 'fengshui.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Improved Heroku detection
IS_HEROKU = 'DYNO' in os.environ or 'DATABASE_URL' in os.environ

if IS_HEROKU:
    # Production database settings - use DATABASE_URL provided by Heroku
    DATABASES = {
        "default": dj_database_url.config(
            conn_max_age=600,
            ssl_require=True  # enforce SSL in production
        )
    }
    print("Using PostgreSQL from DATABASE_URL on Heroku")
else:
    # Local development database settings
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }
    print("Using SQLite for local development")

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ====================
# django-allauth Configuration
# ====================

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Session settings - keep users logged in
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Persist across browser sessions
SESSION_SAVE_EVERY_REQUEST = True  # Refresh session on each request

# Account settings (django-allauth 65+ syntax)
ACCOUNT_LOGIN_METHODS = {'username', 'email'}  # Allow both username and email login
ACCOUNT_SIGNUP_FIELDS = ['email', 'username*', 'password1*']  # username and password required, email optional
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # Don't block registration
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_SESSION_REMEMBER = True  # Keep users logged in
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True

# Custom adapter for frictionless signup and social account linking
ACCOUNT_ADAPTER = 'bazi.adapters.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'bazi.adapters.CustomSocialAccountAdapter'

# Redirects
LOGIN_REDIRECT_URL = 'bazi'
LOGOUT_REDIRECT_URL = 'bazi'
ACCOUNT_LOGOUT_REDIRECT_URL = 'bazi'

# Social account settings
SOCIALACCOUNT_AUTO_SIGNUP = True  # Frictionless social signup
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_LOGIN_ON_GET = True  # Allow GET for social login

# Provider-specific settings (credentials via environment variables)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID', ''),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET', ''),
            'key': ''
        }
    },
    'apple': {
        'APP': {
            'client_id': os.environ.get('APPLE_CLIENT_ID', ''),
            'secret': os.environ.get('APPLE_CLIENT_SECRET', ''),
            'key': os.environ.get('APPLE_KEY_ID', ''),
            'settings': {
                'team_id': os.environ.get('APPLE_TEAM_ID', ''),
            }
        }
    }
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
from django.utils.translation import gettext_lazy as _

LANGUAGE_CODE = 'zh-hans'  # Default to Chinese

LANGUAGES = [
    ('zh-hans', _('中文')),
    ('en', _('English')),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
# Use CompressedStaticFilesStorage (NOT CompressedManifestStaticFilesStorage)
# Vite already hashes filenames for cache-busting, so we don't need WhiteNoise to add another hash
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Additional static files directories (Vite build output)
# Only include directories that exist to avoid warnings
_static_dirs = [
    os.path.join(BASE_DIR, 'static'),
]
STATICFILES_DIRS = [d for d in _static_dirs if os.path.exists(d)]

# Django-Vite Configuration
# Default: Use built static files (no FOUC, instant page loads)
# Set VITE_DEV=1 ONLY for HMR during active frontend development (causes FOUC)
VITE_DEV_MODE = os.environ.get('VITE_DEV', '0') == '1'

DJANGO_VITE = {
    "default": {
        "dev_mode": VITE_DEV_MODE,
        "dev_server_host": "localhost",
        "dev_server_port": 5173,
        "manifest_path": os.path.join(BASE_DIR, 'static', 'dist', 'manifest.json'),
        "static_url_prefix": "dist",
    }
}

DATA_DIR = os.path.join(BASE_DIR, 'data')
if not os.path.exists(DATA_DIR):
    os.makedirs(DATA_DIR)
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
