# Generated by Django 4.2.4 on 2025-05-21 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("birth_year", models.IntegerField(verbose_name="出生年")),
                ("birth_month", models.IntegerField(verbose_name="出生月")),
                ("birth_day", models.IntegerField(verbose_name="出生日")),
                ("birth_hour", models.IntegerField(verbose_name="出生时")),
                ("birth_minute", models.IntegerField(verbose_name="出生分")),
                ("is_male", models.BooleanField(default=True, verbose_name="性别")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户八字资料",
                "verbose_name_plural": "用户八字资料",
                "ordering": ["-created_at"],
            },
        ),
    ]
