# Generated by Django 4.2.4 on 2025-05-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bazi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="默认资料"),
        ),
    ]
