# Generated by Django 4.2.4 on 2025-05-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bazi", "0002_userprofile_is_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="day_master_wuxing",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="日主五行"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorable_wuxing",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="有利五行"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_day_master_strong",
            field=models.BooleanField(blank=True, null=True, verbose_name="日主强"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="unfavorable_wuxing",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="不利五行"
            ),
        ),
    ]
